minimum_trust_level_to_create_TOC:
  default: 1
  type: enum
  choices:
    - 0
    - 1
    - 2
    - 3
    - 4
  description:
    en: "The minimum trust level a user must have in order to see the TOC button in the composer"
table_of_contents_icon:
  default: "align-left"
anchor_icon:
  default: "hashtag"
