minimum_trust_level_to_create_TOC:
  default: 0
  type: enum
  choices:
    - 1
    - 2
    - 3
    - 4
composer_toc_text:
  default: "This topic will contain a table of contents"
auto_TOC_categories:
  type: list
  list_type: category
  default: ""
auto_TOC_tags:
  type: list
  list_type: tag
  default: ""
enable_TOC_for_replies:
  default: false
TOC_min_heading:
  default: 3
  min: 1
  max: 10000
